#!/bin/bash

wget \
  --user=$FTP_USER \
  --ask-password \
  --directory-prefix=config/ \
  --force-directories \
  --input-file=files.txt \
  --no-host-directories \
  --no-verbose \
  --timestamping \
  ftp://51.89.67.47/
